layout_spectrum: 0.6706623
typography_spectrum: 0.07300971
color:
  saturation: 0.9245235
  lightness: 0.5713016
  brandStrength: 0.8501093
  rhythmicContrast: 0.3665263
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: MarieArnold
